### ISSUE TITLE
README indicates one of the methods requires an argument, but test won't pass

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/orm-mapping-db-to-ruby-object-lab#20]
all_students_in_grade_X
README describes as follows: 
### The `.all_students_in_grade_X` Method

This is a class method that takes in an argument of grade for which to retrieve the roster. This method should return an array of all students for grade `X`.

However, I could not pass an argument to this method without getting failure. 
Below is the code I ended up using, but it doesn't seem to satisfy the spirit of the method as named. 
i.e....isn't it supposed to provide functionality for retrieving an array of students given an argument of a grade? 
###### 

 CODE I wanted to use: 

  # def self.all_students_in_grade_X(argument)
  #   sql = <<-SQL
  #     SELECT \* FROM students WHERE grade = ?
  #   SQL

  #  DB[:conn].execute(sql, argument)
  # end
###### 

CODE that passed: 

def self.all_students_in_grade_X
    sql = <<-SQL
      SELECT \* FROM students WHERE grade = ?
    SQL

   DB[:conn].execute(sql, "10")
  end

**Comment by AnnJohn** [comment]
thanks for raising this @smithWEBtek. We'll look into this soon.

**Comment by aprietof** [comment]
The student_spec.rb file is missing an argument.
line 185 should look like this:
`tenth_grade = Student.all_students_in_grade_X(10)`
That's it, that should fix it. :)

**Comment by lukegrecki** [comment]
+1 @aprietof has the right and simple fix. I changed it in my spec file.

**Comment by AnnJohn** [comment]
@pletcher a coupe of folks raised this issue. can you look when you get a chance? thanks

**Comment by pletcher** [comment]
https://github.com/learn-co-curriculum/orm-mapping-db-to-ruby-object-lab/commit/8f96fab79e97c47aed4e5b7ab02be7c012849f02
