### ISSUE TITLE
The student_spec.rb file is missing an argument.

### ISSUE THREAD

**Issue by aprietof** [learn-co-curriculum/orm-mapping-db-to-ruby-object-lab#23]
The student_spec.rb file is missing an argument.
line 185 should look like this:
`tenth_grade = Student.all_students_in_grade_X(10)`
That's it, that should fix it. :)

**Comment by aturkewi** [comment]
@antoinfive It looks like there are a couple of issues related to the test you added in a recent PR

**Comment by pletcher** [comment]
https://github.com/learn-co-curriculum/orm-mapping-db-to-ruby-object-lab/commit/8f96fab79e97c47aed4e5b7ab02be7c012849f02
