### ISSUE TITLE
Discrepancy between README and dog_spec.rb

### ISSUE THREAD

**Issue by lynch16** [learn-co-curriculum/orm-mapping-db-to-ruby-object-lab#30]
According to the README (first image, line 3), in dog_spec.rb, the test '::create_table' should first drop table if it exists. It appears this line is missing from the actual spec file (line 42).  This is causing an issue with the test for the create_table method where it says the table dogs already exists.  While that can be addressed by altering the SQL query string, the README explicitly says that the spec will do that for you.

**Comment by gj** [comment]
Hi @lynch16 !

I think this issue may have been raised on the wrong repository. If you verify that it's correct, ping me and I'll take a second look. 🙂

Thanks!
