### ISSUE TITLE
Sometimes you don't need to use .map to pass a test

### ISSUE THREAD

**Issue by mkang85** [learn-co-curriculum/orm-mapping-db-to-ruby-object-lab#37]
Looking at the text specs, as long as there's some elements returned without discerning the content, then the tests will pass, even though it's not really the correct answer. 

For example, for the "First X students in grade 10" portion, I coded this:

`   def self.first_X_students_in_grade_10(x)
    sql = <<-SQL
    SELECT *
    FROM students
    WHERE students.grade = 10
    LIMIT ?
    SQL
    binding.pry
    DB[:conn].execute(sql, x)
  end
`

Please note that before my "end" statement, I did not utilize the "map" method, and I still got the right answer.  From what I see, I returned something like this: 
[[1, "Pat", "10"], [2, "Sam", "10"]]

I got a nested array with the **values** instead of the actual student objects. 

By adding the .map to the sql query, I got this instead:

[#<Student:0x000000033bf670 @grade="10", @id=1, @name="Pat">,
 #<Student:0x000000033bf648 @grade="10", @id=2, @name="Sam">]

Which would seem to be the point of the test, to return student objects. 

I found that other tests were similar, in that returning nested arrays with only 1 element will satisfy the test, but isn't technically correct.  For example, the count of all the students in grade 9. I think the added restriction in the test specs to return something like "student.id" should fix this limitation (just like in the "find by name" method). 

Hope this is correct, let me know if this isn't really an issue. 

Thanks, 

Michael

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#42.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by maxwellbenton** [comment]
Hi @mkang85,

Thank you for providing this feedback. We're in the process of updating these materials and have taken a look at the tests in this lab. We've updated this test to be more specific. It was previously just checking to see if the right number of elements were being returned, but now checks to see if the elements are of the expected class. This should resolve the issue you experienced.

Thank you again for providing feedback and for contributing to a Learn lesson!
