### ISSUE TITLE
self.count_all_students_in_grade_9 returns an integer or a students array?

### ISSUE THREAD

**Issue by arye-eidelman** [learn-co-curriculum/orm-mapping-db-to-ruby-object-lab#38]
The name "__count__\_all_students_in_grade_9" implies that it should return an integer, but the test requires an array of students of the proper length.

```ruby
# test
describe '.count_all_students_in_grade_9' do
  it 'returns an array of all students in grades 9' do
    pat.name = "Pat"
    pat.grade = 12
    pat.save
    sam.name = "Sam"
    sam.grade = 9
    sam.save

    all_in_9 = Student.count_all_students_in_grade_9
    expect(all_in_9.size).to eq(1)
  end
end
```

It should either be renamed as `self.all_students_in_grade_9` or the test should require it to return an integer.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
