### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by drakeltheryuujin** [learn-co-curriculum/orm-mapping-db-to-ruby-object-lab#42]
PROBLEM: Sometimes you don't need to use .map to pass a test #37
NOTIFY: @mkang85

**Comment by maxwellbenton** [comment]
Updated tests to specifically look for the class of the elements being returned - was previously just checking for the number of elements being returned. This solves the issue of any sort of mapped array passing the test mentioned in #37.
