### ISSUE TITLE
DB folder and students.db file removed

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/orm-mapping-db-to-ruby-object-lab#43]
Without the db folder and students.db file, you get errors when running learn. The solution is just to add the db folder and a blank `student.db` file inside it. I recommend either adding them in the master branch or giving instructions in the README to add them.

**Comment by maxwellbenton** [comment]
Hi @micahshute,

Thank you for spotting this and bringing this to our attention. We've added the `students.db` file back in to this lab along, readded appropriate `.db` files in all labs in the ORM section where missing, and believe this issue has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
