### ISSUE TITLE
Line 136

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/orm-mapping-db-to-ruby-object-lab#6]
Spec student_spec.rb line: 136 reads:

`first_student = Student.first_student_in_grade_10`

Throws following error:

<img width="753" alt="screen shot 2015-12-05 at 7 36 10 pm" src="https://cloud.githubusercontent.com/assets/14326883/11609468/81556e88-9b87-11e5-9754-d1d2f3d66a3f.png">

Fix at line: 136:

 `first_student = Student.first_student_in_grade_12`

**Comment by JVThomas** [comment]
Also note the description does not match the actual method tested

Description : Student.first_student_in_grade_12
Actual Method tested : Student.first_student_in_grade_10
